services:
  - type: web
    name: honto-generator
    env: python
    buildCommand: "./.render/build.sh"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEEPAI_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: HUGGINGFACE_API_TOKEN
        sync: false
